---

- name: Create slurm spool directory
  file:
    path: "{{ __slurm_config_merged.SlurmdSpoolDir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  when: slurm_create_dirs
  notify:
    - reload slurmd

- name: Create slurm log directory
  file:
    path: "{{ __slurm_config_merged.SlurmdLogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurm_config_merged.SlurmdLogFile != omit

- name: Include config dir creation tasks
  include_tasks: _inc_create_config_dir.yml
  when: slurm_create_dirs

- name: Create slurm cgroup directory
  file:
    path: "{{ __slurm_cgroup_config_merged.CgroupReleaseAgentDir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurm_cgroup_config_merged.CgroupReleaseAgentDir is defined
  notify:
    - reload slurmd

- name: Install extra execution host configs
  template:
    src: generic.conf.j2
    dest: "{{ slurm_config_dir }}/{{ item.name }}"
    backup: yes
  with_items:
    - name: cgroup.conf
      config: __slurm_cgroup_config_merged
  when: item.config in vars

- name: Update Grub
  include: grub.yml
