---

- name: Create slurm state directory
  file:
    path: "{{ __slurm_config_merged.StateSaveLocation }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0700
    state: directory
  when: slurm_create_dirs
  notify:
    - reload slurmctld

- name: Create slurm log directory
  file:
    path: "{{ __slurm_config_merged.SlurmctldLogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurm_config_merged.SlurmctldLogFile != omit
  
